---
title: "Project 1"
author: "Jared Steinberg"
date: "2/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
data(Marriage, package = "mosaicData")
data("Marriage")
glimpse(Marriage)
```

```{r, message = FALSE}
ggplot(Marriage, aes(x = race, y = age)) + geom_boxplot(aes(fill = person))
```


#Use this one?
```{r, message = FALSE}
plot <- ggplot(Marriage, aes(x = race, y = college, color = person)) + geom_boxplot()
race_data <- filter(Marriage, race == c("White","Black"))
glimpse(race_data)
race_plot <- ggplot(race_data, aes(x = race, y = college, color = person)) + geom_boxplot()
race_plot 
```



```{r, message = FALSE}
ggplot(Marriage, aes(x = person, y = college, color = race)) + geom_boxplot()
```



```{r, message = FALSE}
ggplot(Marriage, aes(x = person, y = age, color = race)) + geom_boxplot()
```
#Use this one
```{r, message = FALSE}
ggplot(Marriage, aes(x = prevconc, y = age, color = person)) + geom_boxplot()
```

```{r, message = FALSE}
ggplot(Marriage, aes(x = person, y = age, color = prevconc)) + geom_boxplot()
``` 


```{r, message = FALSE}
ggplot(Marriage, aes(x = sign, y = age, color = person)) + geom_boxplot()
```

